export const SANS_FONTS: string[] = [
  'Abel',
  'Acme',
  'Albert Sans',
  'Alegreya Sans',
  'Almarai',
  'Archivo',
  'Archivo Narrow',
  'Arimo',
  'Armata',
  'Asap',
  'Assistant',
  'Atkinson Hyperlegible',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Be Vietnam Pro',
  'Bricolage Grotesque',
  'Cabin',
  'Cairo',
  'Cantarell',
  'Carlito',
  'Catamaran',
  'Chakra Petch',
  'Chivo',
  'Commissioner',
  'DM Sans',
  'Darker Grotesque',
  'Dosis',
  'Encode Sans',
  'Epilogue',
  'Exo 2',
  'Familjen Grotesk',
  'Figtree',
  'Finlandica',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fjalla One',
  'Francois One',
  'Funnel Sans',
  'Geist',
  'Geologica',
  'Golos Text',
  'Gothic A1',
  'Hanken Grotesk',
  'Heebo',
  'Hind',
  'Hind Siliguri',
  'Host Grotesk',
  'IBM Plex Sans',
  'IBM Plex Sans Condensed',
  'Inclusive Sans',
  'Inria Sans',
  'Instrument Sans',
  'Inter',
  'Inter Tight',
  'Jaldi',
  'Josefin Sans',
  'Jost',
  'Kanit',
  'Karla',
  'Khand',
  'Kulim Park',
  'Kumbh Sans',
  'Lato',
  'League Spartan',
  'Lexend',
  'Lexend Deca',
  'Libre Franklin',
  'Livvic',
  'M PLUS Rounded 1c',
  'Manrope',
  'Maven Pro',
  'Merriweather Sans',
  'Metrophobic',
  'Monda',
  'Montserrat',
  'Montserrat Alternates',
  'Mukta',
  'Mulish',
  'Noto Sans',
  'Noto Sans Display',
  'Nunito',
  'Nunito Sans',
  'Onest',
  'Open Sans',
  'Outfit',
  'Overpass',
  'Oxygen',
  'PT Sans',
  'PT Sans Narrow',
  'Pathway Extreme',
  'Play',
  'Plus Jakarta Sans',
  'Poppins',
  'Prompt',
  'Proza Libre',
  'Public Sans',
  'Questrial',
  'Quicksand',
  'Rajdhani',
  'Raleway',
  'Readex Pro',
  'Red Hat Display',
  'Red Hat Text',
  'Rethink Sans',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'Rubik',
  'Ruda',
  'SUSE',
  'Saira',
  'Sarabun',
  'Schibsted Grotesk',
  'Sen',
  'Share Tech',
  'Signika',
  'Sofia Sans',
  'Sono',
  'Sora',
  'Source Sans 3',
  'Space Grotesk',
  'Spline Sans',
  'Teko',
  'Titillium Web',
  'Ubuntu',
  'Ubuntu Sans',
  'Urbanist',
  'Varela Round',
  'Varta',
  'Wix Madefor Display',
  'Wix Madefor Text',
  'Work Sans',
  'Yantramanav',
  'Ysabeau',
  'Zen Kaku Gothic New',
];
