export { SANS_FONTS } from './editorFontDataSans';

export const SERIF_FONTS: string[] = [
  'Aleo',
  'Alegreya',
  'Arvo',
  'Bitter',
  'Bodoni Moda',
  'Bona Nova',
  'Brygada 1918',
  'Cardo',
  'Cinzel',
  'Cormorant',
  'Cormorant Garamond',
  'Crimson Pro',
  'Crimson Text',
  'DM Serif Display',
  'DM Serif Text',
  'Domine',
  'EB Garamond',
  'Eczar',
  'Enriqueta',
  'Faustina',
  'Frank Ruhl Libre',
  'Fraunces',
  'Gelasio',
  'Gentium Book Plus',
  'Gloock',
  'Hepta Slab',
  'IBM Plex Serif',
  'Inria Serif',
  'Instrument Serif',
  'Josefin Slab',
  'Kadwa',
  'Karma',
  'Kreon',
  'Labrada',
  'Libre Baskerville',
  'Libre Bodoni',
  'Libre Caslon Text',
  'Literata',
  'Lora',
  'Merriweather',
  'Neuton',
  'Newsreader',
  'Noticia Text',
  'Noto Serif',
  'Noto Serif Display',
  'PT Serif',
  'Piazzolla',
  'Playfair Display',
  'Podkova',
  'Roboto Serif',
  'Roboto Slab',
  'Rokkitt',
  'Source Serif 4',
  'Spectral',
  'Tinos',
  'Vollkorn',
  'Young Serif',
  'Yrsa',
  'Zilla Slab',
];

export const DISPLAY_FONTS: string[] = [
  'Abril Fatface',
  'Alfa Slab One',
  'Audiowide',
  'Bangers',
  'Bebas Neue',
  'Big Shoulders Display',
  'Black Ops One',
  'Bungee',
  'Calistoga',
  'Cherry Cream Soda',
  'Climate Crisis',
  'Comfortaa',
  'Concert One',
  'DynaPuff',
  'Electrolize',
  'Fredoka',
  'Fugaz One',
  'Gabarito',
  'Goldman',
  'Grandstander',
  'Kablammo',
  'Kelly Slab',
  'Lemon',
  'Lemonada',
  'Lilita One',
  'Limelight',
  'Lobster',
  'Lobster Two',
  'Monoton',
  'MuseoModerno',
  'Nabla',
  'Orbitron',
  'Oxanium',
  'Passion One',
  'Patua One',
  'Pixelify Sans',
  'Press Start 2P',
  'Protest Guerrilla',
  'Righteous',
  'Rowdies',
  'Rubik Vinyl',
  'Russo One',
  'Shrikhand',
  'Silkscreen',
  'Squada One',
  'Staatliches',
  'Titan One',
  'Tourney',
  'Turret Road',
  'Unbounded',
];

export const MONO_FONTS: string[] = [
  'Anonymous Pro',
  'Azeret Mono',
  'Cousine',
  'DM Mono',
  'Fira Code',
  'Fira Mono',
  'Fragment Mono',
  'Geist Mono',
  'IBM Plex Mono',
  'Inconsolata',
  'JetBrains Mono',
  'Martian Mono',
  'Overpass Mono',
  'PT Mono',
  'Red Hat Mono',
  'Roboto Mono',
  'Source Code Pro',
  'Space Mono',
  'Ubuntu Mono',
  'Victor Mono',
];

export const HANDWRITING_FONTS: string[] = [
  'Amatic SC',
  'Architects Daughter',
  'Caveat',
  'Comic Neue',
  'Courgette',
  'Covered By Your Grace',
  'Dancing Script',
  'Gloria Hallelujah',
  'Great Vibes',
  'Handlee',
  'Indie Flower',
  'Itim',
  'Kalam',
  'Mali',
  'Merienda',
  'Neucha',
  'Pacifico',
  'Pangolin',
  'Patrick Hand',
  'Permanent Marker',
  'Playpen Sans',
  'Rock Salt',
  'Sacramento',
  'Satisfy',
  'Shadows Into Light',
  'Short Stack',
  'Sriracha',
];
