import type { TalvexCategorie, TalvexFonction } from './fonctionsTalvexTypes';

export const SEED_CATEGORIES: TalvexCategorie[] = [
  { id: 'cat-superadmin', label: 'Super Admin', order: 0 },
  { id: 'cat-liste-admins', label: 'Liste admins / societes clientes', order: 1 },
  { id: 'cat-panel-admin', label: 'Panel Admin', order: 2 },
  { id: 'cat-panel-vendeur', label: 'Panel Vendeur', order: 3 },
  { id: 'cat-panel-client', label: 'Panel Client', order: 4 },
  { id: 'cat-crm-admin', label: 'CRM Admin', order: 5 },
  { id: 'cat-import-leads', label: 'Import de leads', order: 6 },
  { id: 'cat-crm-societe', label: 'CRM Societe', order: 7 },
  { id: 'cat-sites-domaines', label: 'Sites & Domaines', order: 8 },
  { id: 'cat-messages-chat', label: 'Messages / Chat', order: 9 },
  { id: 'cat-agenda-rdv', label: 'Agenda / RDV', order: 10 },
  { id: 'cat-themes', label: 'Themes', order: 11 },
  { id: 'cat-fuseaux', label: 'Fuseaux horaires', order: 12 },
  { id: 'cat-documentation', label: 'Documentation CRM', order: 13 },
  { id: 'cat-audit', label: 'Audit technique', order: 14 },
  { id: 'cat-sauvegarde', label: 'Sauvegarde / restauration', order: 15 },
  { id: 'cat-api-ia', label: 'API IA / DeepSeek', order: 16 },
  { id: 'cat-bdd', label: 'Base de donnees / Supabase', order: 17 },
];

const now = new Date().toISOString();

export const SEED_FONCTIONS: TalvexFonction[] = [
  {
    id: 'fn-liste-admins',
    categoryId: 'cat-liste-admins',
    titre: 'Liste admins',
    descriptionCourte: 'Permet au Super Admin de gerer toutes les societes clientes de Talvex.',
    descriptionDetaillee: 'Chaque admin represente une societe cliente. Depuis cette liste, le Super Admin peut voir les informations principales des societes, creer un admin, activer ou desactiver l\'acces, selectionner un ou plusieurs admins, supprimer une societe, ouvrir les details, envoyer une annonce, ouvrir la messagerie ou se connecter directement au panel Admin.',
    roleTalvex: 'Centraliser toutes les societes clientes dans une seule plateforme, sans exporter un projet independant pour chaque client.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise l\'Edge Function list-admins pour recuperer les comptes. Les donnees sont mises en cache dans le dashboard Super Admin.',
    updatedAt: now,
  },
  {
    id: 'fn-acces-admin',
    categoryId: 'cat-liste-admins',
    titre: 'Acces admin',
    descriptionCourte: 'Permet d\'autoriser ou bloquer la connexion d\'une societe cliente.',
    descriptionDetaillee: 'Le bouton Acces permet au Super Admin d\'activer ou de desactiver la connexion d\'une societe cliente a son panel Admin. Si l\'acces est desactive, l\'admin ne peut plus se connecter, mais les donnees de la societe restent enregistrees dans Talvex.',
    roleTalvex: 'Proteger l\'acces a la plateforme et controler quelles societes peuvent se connecter.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise toggle-admin-access Edge Function. Le flag access_enabled est stocke dans app_metadata.',
    updatedAt: now,
  },
  {
    id: 'fn-suppression-admin',
    categoryId: 'cat-liste-admins',
    titre: 'Suppression complete admin',
    descriptionCourte: 'Supprime completement une societe cliente et ses donnees liees.',
    descriptionDetaillee: 'La suppression d\'un admin doit supprimer a 100% l\'admin, la societe, les leads, vendeurs, clients, messages, conversations, RDV, commentaires, annonces, pages, configurations, donnees liees et comptes Auth concernes. L\'objectif est d\'eviter toute donnee orpheline.',
    roleTalvex: 'Garantir un nettoyage complet lorsqu\'une societe cliente est retiree de Talvex.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise l\'Edge Function delete-admins avec cascade. Supprime les donnees dans toutes les tables liees par company_id puis le compte Auth.',
    updatedAt: now,
  },
  {
    id: 'fn-connecter-admin',
    categoryId: 'cat-liste-admins',
    titre: 'Connecter',
    descriptionCourte: 'Permet d\'entrer directement dans le panel Admin d\'une societe cliente.',
    descriptionDetaillee: 'Le bouton Connecter permet au Super Admin d\'acceder directement au panel Admin d\'une societe cliente, sans passer par la page d\'accueil publique. Cela permet de verifier, aider, corriger ou visualiser l\'espace de la societe.',
    roleTalvex: 'Offrir un acces direct pour le support et la supervision des societes clientes.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise le systeme d\'impersonation : setImpersonatedAdmin dans App.tsx. Le contexte de retour est sauvegarde via connectReturnContext.',
    updatedAt: now,
  },
  {
    id: 'fn-msg-admin',
    categoryId: 'cat-liste-admins',
    titre: 'MSG',
    descriptionCourte: 'Permet de communiquer avec l\'admin d\'une societe cliente.',
    descriptionDetaillee: 'Le bouton MSG ouvre la messagerie entre le Super Admin et l\'admin/societe cliente afin de communiquer directement depuis Talvex.',
    roleTalvex: 'Communication directe entre le Super Admin et les societes clientes sans outil externe.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise la table super_admin_messages avec RLS. Chat en temps reel via Supabase Realtime.',
    updatedAt: now,
  },
  {
    id: 'fn-annonce-admin',
    categoryId: 'cat-liste-admins',
    titre: 'Annonce',
    descriptionCourte: 'Permet d\'envoyer ou gerer une annonce liee a une societe cliente.',
    descriptionDetaillee: 'Le bouton Annonce permet au Super Admin de transmettre une information importante ou une annonce a une societe cliente.',
    roleTalvex: 'Diffuser des informations importantes aux societes clientes de maniere centralisee.',
    utilisateurs: 'Super Admin',
    etat: 'actif',
    notesTechniques: 'Utilise la table admin_announcements. Les annonces sont affichees dans le TopBar du panel Admin.',
    updatedAt: now,
  },
];

export const VISION_TALVEX = 'Talvex centralise toutes les societes clientes dans une seule plateforme. Chaque societe garde son propre espace, sa page publique et plus tard son domaine, mais le Super Admin conserve le controle sans devoir exporter un dossier independant pour chaque client.';
