/*
  # Chat Automation with DeepSeek AI

  1. Modified Tables
    - `client_messages`
      - `is_ai_reply` (boolean, default false) - marks messages generated by AI
      - `ai_source` (text, nullable) - AI provider identifier (e.g. 'deepseek-chat')
      - `replied_to_message_id` (uuid, nullable) - references the client message that triggered this AI reply

  2. New Tables
    - `chat_automation_config`
      - `id` (uuid, primary key)
      - `company_id` (uuid, unique, FK to companies) - one config per company
      - `enabled` (boolean, default false) - AI toggle, disabled by default
      - `system_prompt` (text) - custom system prompt for the AI
      - `model` (text, default 'deepseek-chat') - AI model identifier
      - `created_at` (timestamptz)
      - `updated_at` (timestamptz)

  3. Security
    - RLS enabled on `chat_automation_config`
    - Admin can only read/write config for their own company (via auth.jwt()->>'company_id')
    - Super admin can read/write all configs
    - Clients and vendors cannot access the config table
    - Policies enforce company_id ownership checks

  4. Important Notes
    - AI is disabled by default (enabled = false)
    - Admin must manually activate via toggle
    - replied_to_message_id prevents duplicate AI replies to the same message
*/

-- 1. Add AI columns to client_messages
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'client_messages' AND column_name = 'is_ai_reply'
  ) THEN
    ALTER TABLE client_messages ADD COLUMN is_ai_reply boolean NOT NULL DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'client_messages' AND column_name = 'ai_source'
  ) THEN
    ALTER TABLE client_messages ADD COLUMN ai_source text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'client_messages' AND column_name = 'replied_to_message_id'
  ) THEN
    ALTER TABLE client_messages ADD COLUMN replied_to_message_id uuid;
  END IF;
END $$;

-- 2. Create chat_automation_config table
CREATE TABLE IF NOT EXISTS chat_automation_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT false,
  system_prompt text NOT NULL DEFAULT 'Vous êtes l''assistant support Talvex. Répondez en français, de manière courte et professionnelle. Ne promettez jamais de prix, contrat ou rendez-vous. Si la question dépasse vos compétences, indiquez qu''un conseiller peut reprendre la conversation.',
  model text NOT NULL DEFAULT 'deepseek-chat',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Enable RLS
ALTER TABLE chat_automation_config ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies - Admin can manage their own company config
CREATE POLICY "Admin can read own company automation config"
  ON chat_automation_config
  FOR SELECT
  TO authenticated
  USING (
    company_id::text = (auth.jwt() -> 'app_metadata' ->> 'company_id')
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin'
  );

CREATE POLICY "Admin can insert own company automation config"
  ON chat_automation_config
  FOR INSERT
  TO authenticated
  WITH CHECK (
    (
      company_id::text = (auth.jwt() -> 'app_metadata' ->> 'company_id')
      AND (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    )
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin'
  );

CREATE POLICY "Admin can update own company automation config"
  ON chat_automation_config
  FOR UPDATE
  TO authenticated
  USING (
    (
      company_id::text = (auth.jwt() -> 'app_metadata' ->> 'company_id')
      AND (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    )
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin'
  )
  WITH CHECK (
    (
      company_id::text = (auth.jwt() -> 'app_metadata' ->> 'company_id')
      AND (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    )
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin'
  );

CREATE POLICY "Admin can delete own company automation config"
  ON chat_automation_config
  FOR DELETE
  TO authenticated
  USING (
    (
      company_id::text = (auth.jwt() -> 'app_metadata' ->> 'company_id')
      AND (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    )
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'super_admin'
  );

-- 5. Index for fast lookup by replied_to_message_id (anti-duplicate check)
CREATE INDEX IF NOT EXISTS idx_client_messages_replied_to
  ON client_messages(replied_to_message_id)
  WHERE replied_to_message_id IS NOT NULL;